/**
 * Hand-authored pixel art. Each sprite is a list of rows; each character maps to a palette colour.
 * '.' is transparent. Sprites are rasterised once into canvases and cached.
 */

export const PAL: Record<string, string> = {
  k: '#1a1423',
  K: '#3b2d3f',
  w: '#f6f2ea',
  W: '#cfc8bd',
  g: '#9aa0a8',
  G: '#686f7c',
  j: '#4a4f5c',
  b: '#5e3a22',
  B: '#86532e',
  n: '#b07a45',
  t: '#d6a464',
  T: '#efcf95',
  y: '#f7d55c',
  Y: '#eaa53a',
  o: '#e06c2e',
  r: '#c43d2f',
  R: '#842a2a',
  l: '#86cf53',
  L: '#4f9a3a',
  d: '#2f6b35',
  D: '#1d4227',
  c: '#6cc0ea',
  C: '#2f6fae',
  p: '#9a78e0',
  P: '#5b3f9c',
  h: '#f0c08c',
  H: '#c58650',
  m: '#5d3b2a',
  x: '#3a3b47',
  z: '#c3cad4',
  e: '#e3cf98',
  E: '#bfa66b',
  f: '#ef8fb5',
  q: '#2a2030',
  // placeholders recoloured per instance
  S: '#ff00ff',
  A: '#00ffff',
  U: '#ffff00',
};

type Rows = string[];

const cache = new Map<string, HTMLCanvasElement>();

export function makeCanvas(w: number, h: number): HTMLCanvasElement {
  const c = document.createElement('canvas');
  c.width = w;
  c.height = h;
  return c;
}

export function raster(rows: Rows, pal: Record<string, string> = PAL): HTMLCanvasElement {
  const h = rows.length;
  const w = Math.max(...rows.map((r) => r.length));
  const c = makeCanvas(w, h);
  const ctx = c.getContext('2d')!;
  for (let y = 0; y < h; y++) {
    const row = rows[y];
    for (let x = 0; x < row.length; x++) {
      const ch = row[x];
      if (ch === '.' || ch === ' ') continue;
      const col = pal[ch] ?? PAL[ch];
      if (!col) continue;
      ctx.fillStyle = col;
      ctx.fillRect(x, y, 1, 1);
    }
  }
  return c;
}

export function sprite(name: string, overrides?: Record<string, string>): HTMLCanvasElement {
  const key = overrides ? name + JSON.stringify(overrides) : name;
  let c = cache.get(key);
  if (!c) {
    const rows = ART[name];
    if (!rows) throw new Error('Unknown sprite ' + name);
    c = raster(rows, overrides ? { ...PAL, ...overrides } : PAL);
    cache.set(key, c);
  }
  return c;
}

/** Data URL of a sprite scaled up for crisp use in the DOM. */
const urlCache = new Map<string, string>();
export function spriteURL(name: string, scale = 2, overrides?: Record<string, string>): string {
  const key = name + scale + JSON.stringify(overrides ?? {});
  let u = urlCache.get(key);
  if (!u) {
    const s = sprite(name, overrides);
    const c = makeCanvas(s.width * scale, s.height * scale);
    const ctx = c.getContext('2d')!;
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(s, 0, 0, c.width, c.height);
    u = c.toDataURL();
    urlCache.set(key, u);
  }
  return u;
}

// ------------------------------------------------------------------ art

export const ART: Record<string, Rows> = {
  // ---------------- buildings (16 wide, bottom-aligned to tile) ----------------
  hut0: [
    '................',
    '.......kk.......',
    '......kBnk......',
    '.....kttnTk.....',
    '....kttTtttk....',
    '...ktTtttTttk...',
    '..kttttTtttTtk..',
    '..ktTttttttttk..',
    '.kttttTtttTtttk.',
    '.ktTttkkkkttTtk.',
    '.ktttkqqqqktttk.',
    'kttTtkqqqqktTttk',
    'kEEEEkqqqqkEEEEk',
    '.kkkkkkkkkkkkkk.',
  ],
  hut1: [
    '................',
    '.......kk.......',
    '.....kkttkk.....',
    '....kttTTttk....',
    '...kttTTTTttk...',
    '..kttTTttTTttk..',
    '.kttTTttttTTttk.',
    'kkkkkkkkkkkkkkkk',
    '.kBnBnBnBnBnBnk.',
    '.kBBkkkBBBkkkBk.',
    '.knBkqkBnBkcknk.',
    '.kBBkqkBBBkkkBk.',
    '.knBkqkBnBnBnBk.',
    '.kBBkqkBBBBBBBk.',
    '.kkkkkkkkkkkkkk.',
  ],
  house: [
    '................',
    '..........kk....',
    '......kk..kGk...',
    '....kkrrkkkGk...',
    '...krrRRrrkGk...',
    '..krrRRRRrrkk...',
    '.krrRRrrRRrrrk..',
    'krrRRrrrrRRrrrk.',
    'kkkkkkkkkkkkkkkk',
    '.kWgWgWgWgWgWgk.',
    '.kgWkkkWgWkkkWk.',
    '.kWgkqkgWgkykgk.',
    '.kgWkqkWgWkkkWk.',
    '.kWgkqkgWgWgWgk.',
    '.kGGkqkGGGGGGGk.',
    '.kkkkkkkkkkkkkk.',
  ],
  lumber: [
    '................',
    '................',
    '.......kk.......',
    '......kzzk......',
    '......kzGk......',
    '.......kbk......',
    '......kkBkkkk...',
    '.....kBnnnnBTk..',
    '.....knBBBBnTk..',
    '.kkkkkkkkkkkkk..',
    'kTtkBnnBnnBnnBk.',
    'kTtknBBnBBnBBnk.',
    'kkkkkkkkkkkkkkk.',
    'kTtkBnnBnnBnnBk.',
    'kTtknBBnBBnBBnk.',
    '.kkkkkkkkkkkkk..',
  ],
  lodge: [
    '................',
    '..k.k.....k.k...',
    '..knkk...kknk...',
    '...kntk.ktnk....',
    '....kkTTTkk.....',
    '...kTTttTTtk....',
    '..kTttTTttTtk...',
    '.kttTTttttTTtk..',
    'kkkkkkkkkkkkkkk.',
    '.kbBbBbBbBbBbk..',
    '.kBbkkkkBbBbBk..',
    '.kbBkqqkbkrkbk..',
    '.kBbkqqkBkRkBk..',
    '.kbBkqqkbBbBbk..',
    '.kkkkkkkkkkkkk..',
  ],
  storehouse: [
    '................',
    '................',
    '...kkkkkkkkkk...',
    '..kBnBnBnBnBnk..',
    '.kBnBnBnBnBnBnk.',
    'kkkkkkkkkkkkkkkk',
    '.knBBBBBBBBBBnk.',
    '.kBkkkkkkkkkkBk.',
    '.knkTtTkkTtTknk.',
    '.kBkTkTkkTkTkBk.',
    '.knkTtTkkTtTknk.',
    '.kBkkkkkkkkkkBk.',
    '.knBBBBBBBBBBnk.',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  quarry: [
    '................',
    '................',
    '................',
    '....kkkkk.......',
    '...kWgWgGk..kk..',
    '..kWgggGGGkkgGk.',
    '.kWggGkkGGkgGGk.',
    '.kgGGk..kGkkkk..',
    '.kGGk.zk.kk.....',
    '..kk.kzk.kkkk...',
    '.....kbk.kWgGk..',
    '..kkkkbk.kgGGk..',
    '.kWgWkbk.kkkk...',
    '.kgGGk...kWgGk..',
    '.kkkkk...kkkkk..',
  ],
  farm: [
    '................',
    '................',
    '................',
    '................',
    'kkkkkkkkkkkkkkkk',
    'k1U1U1U1U1U1U1Uk',
    'kUUUUUUUUUUUUUUk',
    'k1U1U1U1U1U1U1Uk',
    'kUUUUUUUUUUUUUUk',
    'k1U1U1U1U1U1U1Uk',
    'kUUUUUUUUUUUUUUk',
    'k1U1U1U1U1U1U1Uk',
    'kUUUUUUUUUUUUUUk',
    'k1U1U1U1U1U1U1Uk',
    'kkkkkkkkkkkkkkkk',
  ],
  granary: [
    '................',
    '.......kk.......',
    '......kTTk......',
    '.....kTttTk.....',
    '....kTttttTk....',
    '...kTttTTtttk...',
    '..kTtttttttttk..',
    '..kkkkkkkkkkkk..',
    '..kHhHHhHHhHHk..',
    '..khHHhkkhHHhk..',
    '..kHHhkqqkhHHk..',
    '..khHHkqqkHHhk..',
    '..kHhHkqqkHhHk..',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  watchtower: [
    '....kkkkkkkk....',
    '...kTtTtTtTtk...',
    '..kttTtTtTtTtk..',
    '.kkkkkkkkkkkkkk.',
    '..kBnkBnBnkBnk..',
    '..kBkqqqqqqkBk..',
    '..kkkkkkkkkkkk..',
    '...kBk....kBk...',
    '...knkk..kknk...',
    '...kBk.kk.kBk...',
    '...knkk..kknk...',
    '...kBk.kk.kBk...',
    '...knkk..kknk...',
    '...kBk.kk.kBk...',
    '...knkk..kknk...',
    '...kBk....kBk...',
    '..kkBkk..kkBkk..',
    '..kGgGk..kGgGk..',
    '..kkkkk..kkkkk..',
  ],
  herbalist: [
    '................',
    '..........l.....',
    '.......kkLlL....',
    '......kddkLk....',
    '.....kdLLdk.....',
    '....kdLLLLdk....',
    '...kdLLdLLLdk...',
    '..kdLLLLLdLLdk..',
    '.kkkkkkkkkkkkkk.',
    '..kBnBnBnBnBnk..',
    '..knkkkknBnBnk..',
    '..kBkqqkBkfkBk..',
    '..knkqqknkLknk..',
    '..kBkqqkBnBnBk..',
    '..kkkkkkkkkkkk..',
    '.kLlk.....kLlk..',
  ],
  pasture: [
    '................',
    '................',
    '................',
    '................',
    '.kk..kk..kk..kk.',
    'kBnkkBnkkBnkkBnk',
    'kkkkkkkkkkkkkkkk',
    '.kk...kkkk...kk.',
    '.kk..kwwwwk..kk.',
    '.kk.kWwwwwwk.kk.',
    'kkkkkwwwwwWkkkkk',
    'kBnkkWwWwwWkkBnk',
    'kkkk.kGkkGk.kkkk',
    '.kk..kk..kk..kk.',
    '................',
  ],
  mine: [
    '................',
    '................',
    '.....kkkkk......',
    '...kkgGGGgkk....',
    '..kgGGjjjGGgk...',
    '.kgGkkkkkkkGgk..',
    '.kGkBnBnBnBkGk..',
    'kgGknkqqqknkGgk.',
    'kGGkBkqqqkBkGGk.',
    'kgGknkqqqknkGgk.',
    'kGGkBkqqqkBkGGk.',
    'kkkkkkkzkkkkkkk.',
    '....kxzzzzxk....',
    '....kxyGyGxk....',
    '.....kk..kk.....',
  ],
  smithy: [
    '...........kk...',
    '..........kGGk..',
    '..........kgGk..',
    '....kkkkkkkgGk..',
    '...kxjxjxjxjGk..',
    '..kxjxjxjxjxjxk.',
    '.kkkkkkkkkkkkkkk',
    '.kWgWgWgWgWgWgk.',
    '.kgWkkkkkgWgWgk.',
    '.kWkoYyYokWgWgk.',
    '.kgkYyyyYkkkkWk.',
    '.kWkoYyYokxxxkk.',
    '.kgWkkkkkkzxzkk.',
    '.kGGGGGGGGkxkGk.',
    '.kkkkkkkkkkkkkk.',
  ],
  library: [
    '................',
    '.......kk.......',
    '.....kkwwkk.....',
    '...kkwwWWwwkk...',
    '.kkwwWWWWWWwwkk.',
    'kkkkkkkkkkkkkkkk',
    '.kwwwwwwwwwwwwk.',
    '.kkWkkWkkWkkWkk.',
    '..kwk.kwkkwk.k..',
    '..kWkqkWkkWkqk..',
    '..kwkqkwkkwkqk..',
    '..kWkqkWkkWkqk..',
    '..kwk.kwkkwk.k..',
    '.kkkkkkkkkkkkkk.',
    'kWWWWWWWWWWWWWWk',
    'kkkkkkkkkkkkkkkk',
  ],
  shrine: [
    '.......kk.......',
    '......kyyk......',
    '.....kyYYyk.....',
    '......kyyk......',
    '.......kk.......',
    '.....kkwwkk.....',
    '...kkwwWWwwkk...',
    '.kkwwWWWWWWwwkk.',
    'kkkkkkkkkkkkkkkk',
    '.kwwwwwwwwwwwwk.',
    '.kkkkkkkkkkkkkk.',
    '..kwk.kwkkwk.k..',
    '..kWk.kWkkWkpk..',
    '..kwk.kwkkwkPk..',
    '..kWk.kWkkWkpk..',
    '..kwk.kwkkwkPk..',
    '..kWk.kWkkWk.k..',
    '.kkkkkkkkkkkkkk.',
    'kWWWWWWWWWWWWWWk',
    'kkkkkkkkkkkkkkkk',
  ],
  site: [
    '................',
    '................',
    '................',
    '..k.........k...',
    '..nk.......kn...',
    '..n.k.....k.n...',
    '..n..k...k..n...',
    'knnnnnnnnnnnnnk.',
    '..n...k.k...n...',
    '..n....k....n...',
    '..n...k.k...n...',
    '..n..k...k..n...',
    '.kWk.......kGgk.',
    'kWgGk.kbk.kGgGk.',
    'kkkkk.kBk.kkkkk.',
    '................',
  ],
  // the great hearth: stone ring & logs; flames are drawn procedurally
  campfire: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.kk..........kk.',
    'kBnk........kBnk',
    'kbBk..kkkk..kbBk',
    '.kk.kgWggWk..kk.',
    '...kgkbnnbkgk...',
    '...kWkBnnBkWk...',
    '...kgWkkkkWgk...',
    '.kk.kgWGGgk.kk..',
    'kBnk.kkkkk.kBnk.',
    'kbBk.......kbBk.',
    '.kk.........kk..',
  ],

  // ---------------- terrain decorations ----------------
  pine: [
    '....DD....',
    '...DlLD...',
    '...DLdD...',
    '..DlLLdD..',
    '..DLLddD..',
    '.DlLLLddD.',
    '..DLLddD..',
    '.DlLLLddD.',
    'DlLLLLdddD',
    'DLLLLddddD',
    '.DDDDDDDD.',
    '....bm....',
    '....bm....',
  ],
  oak: [
    '...DDDDD...',
    '.DDlLLLLDD.',
    'DlLLlLLLLdD',
    'DLlLLLLlLdD',
    'DLLLLLLLLdD',
    'DdLLLLLLddD',
    '.DdLLLLdddD',
    '..DDdddDDD.',
    '....DbmD...',
    '.....bm....',
    '.....bm....',
    '....bbmb...',
  ],
  bush: ['..DDDD..', '.DlLLdD.', 'DlLLLLdD', 'DLLLLddD', '.DDDDDD.'],
  berries: ['..DDDD..', '.DlrLdD.', 'DlLLrLdD', 'DrLLLrdD', '.DDDDDD.'],
  rock: ['..kkk...', '.kWggk..', 'kWgggGk.', 'kgGGGGk.', '.kkkkk..'],
  reeds: ['.l..l.', '.L.lL.', 'lL.LL.', 'LL.Ld.', 'Ld.dd.'],
  flowers: ['.y...f.', 'yYy.fpf', '.L...L.'],
  mountain: [
    '.......kk.......',
    '......kWgk......',
    '.....kWggGk.....',
    '.....kgggGk.....',
    '....kWgggGGk....',
    '....kggggGGk....',
    '...kWgggGGGGk...',
    '...kgggggGGGk...',
    '..kWggggGGGGGk..',
    '..kgggggGGGGjk..',
    '.kWgggggGGGGjjk.',
    '.kgggggGGGGGjjk.',
    'kWggggggGGGGjjjk',
    'kgggggggGGGjjjjk',
    'kkkkkkkkkkkkkkkk',
  ],
  peak: [
    '.......kk.......',
    '......kwwk......',
    '.....kwwwWk.....',
    '.....kwwWWk.....',
    '....kwwwWWWk....',
    '....kwWwgWGk....',
    '...kWwgggGGGk...',
    '...kgWgggGGGk...',
    '..kWggggGGGGGk..',
    '..kgggggGGGGjk..',
    '.kWgggggGGGGjjk.',
    '.kgggggGGGGGjjk.',
    'kWggggggGGGGjjjk',
    'kgggggggGGGjjjjk',
    'kkkkkkkkkkkkkkkk',
  ],
  hill: [
    '................',
    '................',
    '.....DDDDD......',
    '...DDlllLLDD....',
    '..DllLLLLLLdD...',
    '.DlLLLLLLLLddD..',
    'DLLLLLLLLLdddDD.',
    'DDDDDDDDDDDDDDDD',
  ],
  ruins: [
    '................',
    '..kk............',
    '.kWgk.....kk....',
    '.kgGk....kWgk...',
    '.kWgk....kgGk...',
    '.kgGk.kk.kWgk...',
    '.kWgkkWgkkgGk...',
    '.kgGkkgGkkWgk...',
    'kkkkkkkkkkkkkk..',
    'kWgWgkgWgWgGgk..',
    'kkkkkkkkkkkkkk..',
  ],
  tents: [
    '....k.....k.....',
    '...kTk...krk....',
    '..kTtTk.krRrk...',
    '.kTtkTtkrRkRrk..',
    'kTtkqkTkRkqkRrk.',
    'kkkkkkkkkkkkkkk.',
  ],
  grove: [
    '....DDDDDD....',
    '..DDlLLLLlDD..',
    '.DlLLyLLLLLdD.',
    'DlLLLLLLyLLLdD',
    'DLLyLLLLLLLddD',
    'DdLLLLLyLLdddD',
    '.DddLLLLLdddD.',
    '..DDDdddDDDD..',
    '.....DbmD.....',
    '...y..bm..y...',
    '.....bbmmb....',
  ],
  cache: ['..kkkkkk..', '.kTtTtTtk.', 'kkkkkkkkkk', 'kBnBkyknBk', 'knBnkkkBnk', 'kBnBnBnBnk', 'kkkkkkkkkk'],
  ore: ['..k...', '.kyk..', 'kyYk.k', '.kk.kc', '....k.'],

  // ---------------- creatures ----------------
  // S = shirt, A = hair, U = trousers
  person0: ['..AAA..', '.AhhhA.', '..hhh..', '.SSSSS.', 'hSSSSSh', '.SSSSS.', '..UUU..', '..U.U..', '..U.U..', '..k.k..'],
  person1: ['..AAA..', '.AhhhA.', '..hhh..', '.SSSSS.', 'hSSSSS.', '.SSSSSh', '..UUU..', '..U.U..', '.U...U.', '.k...k.'],
  person2: ['..AAA..', '.AhhhA.', '..hhh..', '.SSSSS.', '.SSSSSh', 'hSSSSS.', '..UUU..', '..U.U..', '..UU...', '..kk...'],
  personWork: ['..AAA.z', '.AhhhAb', '..hhh.b', '.SSSSSh', 'hSSSSS.', '.SSSSS.', '..UUU..', '..U.U..', '..U.U..', '..k.k..'],
  child0: ['.AAA.', '.hhh.', 'SSSSS', '.SSS.', '.U.U.', '.k.k.'],
  child1: ['.AAA.', '.hhh.', 'hSSSh', '.SSS.', 'U...U', 'k...k'],
  deer0: ['.n.n......', '..nn......', '..ntk.....', '...BBBBBB.', '...BnnnnB.', '...B.B.B.B', '...k.k.k.k'],
  deer1: ['.n.n......', '..nn......', '..ntk.....', '...BBBBBB.', '...BnnnnB.', '..B.B..B.B', '..k.k..k.k'],
  sheep: ['.wwww.', 'wwwwwk', 'wWwwwk', '.k..k.'],
  bird0: ['k...k', '.k.k.', '..k..'],
  bird1: ['.....', 'kk.kk', '..k..'],
  fish: ['.c..', 'cCcc', '.c..'],

  // ---------------- UI icons (12x12) ----------------
  i_food: [
    '............',
    '......kkk...',
    '.....kRrrk..',
    '....kRrrrrk.',
    '...kRrrrrrk.',
    '...kRrrrRrk.',
    '...kRrrRrk..',
    '..kwkRRkk...',
    '.kwwkkk.....',
    'kwWk........',
    '.kk.........',
    '............',
  ],
  i_wood: [
    '............',
    '............',
    '..kkkkkkkk..',
    '.kBBnBBBkTk.',
    'kBnBBBBkTtTk',
    'kBBBnBBkTnTk',
    'kBnBBBBkTtTk',
    '.kBBBnBBkTk.',
    '..kkkkkkkk..',
    '............',
    '............',
    '............',
  ],
  i_stone: [
    '............',
    '............',
    '....kkkk....',
    '..kkWWgGkk..',
    '.kWWgggGGGk.',
    '.kWggggGGGk.',
    'kWgggGGGGGjk',
    'kggGGGGGjjjk',
    '.kkkkkkkkkk.',
    '............',
    '............',
    '............',
  ],
  i_hides: [
    '............',
    '..kk....kk..',
    '.kTtkkkktTk.',
    '.ktTttttTtk.',
    '..ktTtTttk..',
    '..kttTttTk..',
    '..kTttTttk..',
    '.ktTtttTtTk.',
    '.kTtkkkktTk.',
    '..kk....kk..',
    '............',
    '............',
  ],
  i_ore: [
    '............',
    '............',
    '.....kkk....',
    '...kkGjGkk..',
    '..kGgycjGjk.',
    '.kGjGgjGyGk.',
    '.kGcGjGcjGk.',
    '.kjGyGjGGjk.',
    '..kkkkkkkk..',
    '............',
    '............',
    '............',
  ],
  i_tools: [
    '............',
    '..kkkkk.....',
    '.kzzWzzk....',
    '.kxzzzxk....',
    '..kkBkk.....',
    '....kBk.....',
    '.....kBk....',
    '......kBk...',
    '.......kBk..',
    '........kBk.',
    '.........kk.',
    '............',
  ],
  i_knowledge: [
    '............',
    '.kkkkkkkkk..',
    'kTtTtTtTtTk.',
    'kTkkkkkkTtk.',
    'ktTttTtttTk.',
    'kTkkkkkTttk.',
    'ktTtTttTtTk.',
    'kTkkkkkkTtk.',
    'ktTtTtTtTtk.',
    '.kkkkkkkkkBk',
    '.........kk.',
    '............',
  ],
  i_people: [
    '............',
    '...kk..kk...',
    '..kmmkkmmk..',
    '..khhkkhhk..',
    '..khhkkhhk..',
    '.kCCCkkrrrk.',
    '.kCCCkkrrrk.',
    '.kCCCkkrrrk.',
    '..kbkkkkbk..',
    '..kbk..kbk..',
    '..kk....kk..',
    '............',
  ],
  i_house: [
    '............',
    '.....kk.....',
    '....kttk....',
    '...kttTtk...',
    '..kttTTttk..',
    '.kttTttTttk.',
    'kkkkkkkkkkkk',
    '.kBnBkkBnBk.',
    '.knBkqqknBk.',
    '.kBnkqqkBnk.',
    '.kkkkkkkkkk.',
    '............',
  ],
  i_morale: [
    '............',
    '....kkkk....',
    '..kkyyyykk..',
    '.kyyyyyyyyk.',
    '.kyykyykyyk.',
    'kyyykyykyyyk',
    'kyyyyyyyyyyk',
    'kyykyyyykyyk',
    '.kyykkkkyyk.',
    '.kyyyyyyyyk.',
    '..kkyyyykk..',
    '....kkkk....',
  ],
  i_spring: [
    '............',
    '.....ff.....',
    '....fwwf....',
    '...ffyyff...',
    '....fwwf....',
    '.....ff.....',
    '.....L......',
    '...l.L......',
    '...lLL..L...',
    '.....L.LL...',
    '.....LL.....',
    '............',
  ],
  i_summer: [
    '.....yy.....',
    '..y..yy..y..',
    '...y....y...',
    '....yyyy....',
    '...yYYYYy...',
    'yy.yYYYYy.yy',
    'yy.yYYYYy.yy',
    '...yYYYYy...',
    '....yyyy....',
    '...y....y...',
    '..y..yy..y..',
    '.....yy.....',
  ],
  i_autumn: [
    '............',
    '.....kk.....',
    '....kook....',
    '...koYYok...',
    '..koYoYYok..',
    '.koYYoYYYok.',
    '.koYYYoYYok.',
    '..koYYYook..',
    '...kooYok...',
    '....kkbk....',
    '......bk....',
    '............',
  ],
  i_winter: [
    '.....cc.....',
    '..c..cc..c..',
    '...c.cc.c...',
    '....cwwc....',
    'cc..cwwc..cc',
    '.cccwwwwccc.',
    '.cccwwwwccc.',
    'cc..cwwc..cc',
    '....cwwc....',
    '...c.cc.c...',
    '..c..cc..c..',
    '.....cc.....',
  ],
  i_scout: [
    '............',
    '....kkkk....',
    '..kkwwwwkk..',
    '.kwwwkkwwwk.',
    'kwwwkCCkwwwk',
    'kwwkCkkCkwwk',
    'kwwkCkkCkwwk',
    'kwwwkCCkwwwk',
    '.kwwwkkwwwk.',
    '..kkwwwwkk..',
    '....kkkk....',
    '............',
  ],
  i_hammer: [
    '............',
    '..kkkkkk....',
    '.kxzzzzxk...',
    '.kxxkkxxk...',
    '..kk.kBk....',
    '.....kBk....',
    '.....kBk....',
    '.....kBk....',
    '.....kBk....',
    '.....kBk....',
    '.....kkk....',
    '............',
  ],
  i_spear: [
    '.........kk.',
    '........kzzk',
    '.......kzzk.',
    '......kBkk..',
    '.....kBk....',
    '....kBk.....',
    '...kBk......',
    '..kBk.......',
    '.kBk........',
    'kBk.........',
    'kk..........',
    '............',
  ],
  i_axe: [
    '............',
    '.....kkk....',
    '....kzzzk...',
    '...kzzzBk...',
    '...kzzBkk...',
    '....kBk.....',
    '...kBk......',
    '..kBk.......',
    '.kBk........',
    'kBk.........',
    'kk..........',
    '............',
  ],
  i_sickle: [
    '............',
    '....kkkk....',
    '...kzzzzk...',
    '..kzkkkkzk..',
    '.kzk....kzk.',
    '.kzk.....kk.',
    '..kzk.......',
    '...kzkk.....',
    '....kkBk....',
    '......kBk...',
    '.......kk...',
    '............',
  ],
  i_pick: [
    '............',
    '..kkkkkkk...',
    '.kzzzzzzzk..',
    'kzkkkBkkkzk.',
    'kk...kBk..kk',
    '......kBk...',
    '.......kBk..',
    '........kBk.',
    '.........kBk',
    '..........kk',
    '............',
    '............',
  ],
  i_anvil: [
    '............',
    '............',
    '.kkkkkkkkk..',
    'kxzzzzzzzxk.',
    '.kxxxxxxxk..',
    '...kxxxk....',
    '...kxxxk....',
    '..kxxxxxk...',
    '.kxxxxxxxk..',
    '.kkkkkkkkk..',
    '............',
    '............',
  ],
  i_herb: [
    '............',
    '......kk....',
    '.....klLk...',
    '..kk.kLdk...',
    '.klLkkLdk...',
    '.kLLdkdk....',
    '..kddkk.kk..',
    '....kLk.klk.',
    '....kLkkLLk.',
    '....kLkLdk..',
    '....kLLdk...',
    '.....kkk....',
  ],
  i_basket: [
    '............',
    '...k.k.k....',
    '..krkrkrk...',
    '.krRrRrRrk..',
    'kkkkkkkkkkk.',
    'ktTtTtTtTtk.',
    'kTtTtTtTtTk.',
    '.ktTtTtTtk..',
    '.kTtTtTtTk..',
    '..kkkkkkk...',
    '............',
    '............',
  ],
  i_star: [
    '.....kk.....',
    '....kyyk....',
    '....kyyk....',
    'kkkkyyyykkkk',
    'kyyyyyyyyyyk',
    '.kyyyYYyyyk.',
    '..kyyYYyyk..',
    '..kyyyyyyk..',
    '.kyyykkyyyk.',
    '.kyyk..kyyk.',
    '.kkk....kkk.',
    '............',
  ],
  i_skull: [
    '............',
    '...kkkkkk...',
    '..kwwwwwwk..',
    '.kwwwwwwwwk.',
    '.kwkkwwkkwk.',
    '.kwkkwwkkwk.',
    '.kwwwkkwwwk.',
    '..kwwwwwwk..',
    '...kwkwkk...',
    '...kkkkkk...',
    '............',
    '............',
  ],
  i_flag: [
    '.kk.........',
    '.kBkkkkkkk..',
    '.kBkoooooook',
    '.kBkoYYoooYk',
    '.kBkooYYooYk',
    '.kBkoooYYook',
    '.kBkkkkkkkkk',
    '.kBk........',
    '.kBk........',
    '.kBk........',
    'kkBkk.......',
    'kGgGk.......',
  ],
  i_heart: [
    '............',
    '.kkk...kkk..',
    'kffwk.kfffk.',
    'kfwffkffffk.',
    'kfffffffRfk.',
    'kffffffffRk.',
    '.kffffffRk..',
    '..kffffRk...',
    '...kffRk....',
    '....kRk.....',
    '.....k......',
    '............',
  ],
};
